### ISSUE TITLE
Question: Application Insights - Write to "exceptions" and not "traces"

### ISSUE THREAD

**Issue by hiraldesai** [Microsoft/ApplicationInsights-dotnet-logging#102]
What do I need to do to write the unhandled exceptions to "exceptions" tab in Application Insights instead of the usual "Traces" tab?

This is what my setup is:
```
            var config = new LoggingConfiguration();
            var target = new ApplicationInsightsTarget
            {
                InstrumentationKey = _instrumentationKey
            };

            var rule = new LoggingRule("*", LogLevel.Trace, target);
            config.LoggingRules.Add(rule);

            LogManager.Configuration = config;
```

And this is how I'm logging:

```
private readonly ILogger<ClassName> _logger;
public ClassName(ILoggerFactory loggerFactory) 
{
_logger = loggerFactory.CreateLogger<CustomErrorHandlingMiddleware>();
}
...
...
_logger.LogError(0, exception, exception.Message);
...
```

Everything is ending up under "traces" tab, nothing under "exceptions" tab.

![image](https://user-images.githubusercontent.com/1005174/28177374-7510bbd2-67af-11e7-9681-3e7daa31d7ad.png)

**Comment by SergeyKanzhelev** [comment]
I get you are using NLog target? It suppose to track exception as long as `LogEventInfo` item has it not empty. See [here](https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/54bcb3e4b2d3e02862d65663c65b32b0ee4afac9/src/Adapters/NLogTarget.Shared/ApplicationInsightsTarget.cs#L81).

Do you know if ILogger -> NLog initializes this field properly? I do not have experience with this combination of loggers.

**Comment by hiraldesai** [comment]
Thank you for the reference @SergeyKanzhelev. Yes, I'm using NLog target, I will look into more details to figure out if it's populating it correctly.

**Comment by SergeyKanzhelev** [comment]
@hiraldesai I'll close the issue for now. Please re-open if you discovered there is an issue that needs to be addressed
