### ISSUE TITLE
Setting cloud_RoleName

### ISSUE THREAD

**Issue by qrli** [Microsoft/ApplicationInsights-dotnet-logging#103]
AI now has better support for differentiating different roles (application components, or microservices), e.g. in Application Map. 

In web application, I can set it with TelemetryInitializer or directly on the TelemetryClient.Context.Cloud.RoleName. But for the logging adapters, I don't find a way to set it.

**Comment by SergeyKanzhelev** [comment]
@qrli you still can use telemetry initializers. Initializer will apply to every telemetry item inclucluding trace collected by logging adaptor.

**Comment by SergeyKanzhelev** [comment]
Please re-open if you need more details or clarifications
