### ISSUE TITLE
Return back Endpoint Validation tests (if needed)

### ISSUE THREAD

**Issue by Dmitry-Matveev** [Microsoft/ApplicationInsights-dotnet-logging#112]
There are three endpoint validation tests `TelemetryIsAcceptedByValidateEndpoint` that send items directly to AI Endpoint to validate against endpoint-accepted schema. Those tests are now disabled because Ikey is no longer valid.
Let's review their necessity and add them back with the appropriate iKeys.

**Comment by SergeyKanzhelev** [comment]
I fixed similar tests in `-dotnet` repo. We decided to remove them from `-dotnet-server` as they were re-validating that serialization of data item works as expected. Potentially the same should be done here

**Comment by SergeyKanzhelev** [comment]
closing task
