### ISSUE TITLE
Adding support for disabledEventSourceNamePrefix configuration

### ISSUE THREAD

**Issue by xiaomi7732** [Microsoft/ApplicationInsights-dotnet-logging#122]
Due to a .NET Framework bug: https://github.com/dotnet/coreclr/issues/14434, there's a discussion providing support for configurations to allow totally disabling some event sources by their name prefixes.
Details of the discussion could be found here: https://github.com/Azure/diagnostics-eventflow/issues/140.

@SergeyKanzhelev, @dnduffy, I am planning to put the implementation into `EventSourceTelemetryModule`.

**Here's a simple description:**
_Configuration:_
![image](https://user-images.githubusercontent.com/3674549/32577525-19a5e5aa-c48f-11e7-8b61-c7cd72a897ff.png)

_Details:_

- Disabling EventSources is not recommended under normal circumstances, however, due to some edge cases, like the bug here: https://github.com/dotnet/coreclr/issues/14434, there needs a way to work-around it.

- For event-source that matches in the 'Sources' exactly and at the same time, starts with disabledEventSourceNamePrefix, the enabling of the source will take the priority because:

  - Exact match should take over partial match;
  - Generally, for telemetry module settings, we are using the opt-in than opt-out;
  - It is flexible that user can express: I want `abc` event source but not anything else that starts with `ab`, because either I don't care or they are having issues.

Please use this issue for feedback on the ideas and I'll submit PR for review when it is implemented.

**Comment by SergeyKanzhelev** [comment]
Can configuration be like this so it will be a single collection? And it will support wildcards for collecting as well.

```
<Sources>
    <Add Name = "MyCompany" Level="Verbose" Include = "true" Wildcard = "false" />
    <Add Name = "Microsoft.ApplicationInsights" Include = "false" Wildcard = "true" />
</Sources>
```

**Comment by xiaomi7732** [comment]
@SergeyKanzhelev,
Thanks for the reply, especially, providing yet another implementation proposal.

Is there any specific reason you want to put them together? Performance gains?

I am leaning toward adding another section because:
1. Having disabling source with level/keywords settings on the rules feels overwhelming;
2. Using 'Add' element inside 'Sources' to prevent some event source events being gathered feels somewhat weird - I know logically, the add is for adding a rule rather than adding a source, but it just feels confusion.

At the same time, I don't see it expensive to support wildcard for opted-in event sources. I can put in the implementations together:

```xml
<Sources>
    <Add Name="MyCompany" Level="Verbose" Wildcard="false" />
    <Add Name="Microsoft.ApplicationInsights" Wildcard="true" />
</Sources>
<DisabledSources>
    <Add Name="SomeBadEventSource" Wildcard="true" />
</DisabledSources>
```

What do you say?

**Comment by SergeyKanzhelev** [comment]
Love the config you proposing!

**Comment by xiaomi7732** [comment]
Great! Thanks for the feedback. I'll put the implementation in.
