### ISSUE TITLE
Unit test is failing for EventSource Listener

### ISSUE THREAD

**Issue by xiaomi7732** [Microsoft/ApplicationInsights-dotnet-logging#127]
The unit tests of 'ReportsAllProperties' recently starts to fail. I have a handle on the commit range causing the trouble but needs some follow up.
I file this issue to track the fix for the unit test.
PR will be provided when issues fixed.

**Comment by xiaomi7732** [comment]
A bit details, it seems the cause is we are losing the report of properties of **ProviderName** and **ProviderGuid**, looks like a regression in the product code. More details to come with, hopefully, a quick fix in form of PR.

**Comment by SergeyKanzhelev** [comment]
Has it started after my PR? I might have caused it. Let me check...

**Comment by SergeyKanzhelev** [comment]
Yep. It was me... Wonder why tests were not failing for me...

**Comment by SergeyKanzhelev** [comment]
@xiaomi7732 sorry for inconvenience. Should be fixed with PR

**Comment by xiaomi7732** [comment]
@SergeyKanzhelev 
Thanks for the quick turn-around. #128 looks good to me.
