### ISSUE TITLE
Does Microsoft. ApplicationInsights. NLogTarget have influence on NLog console and file targets?

### ISSUE THREAD

**Issue by mstao** [Microsoft/ApplicationInsights-dotnet-logging#137]
Hi, I use Microsoft.ApplicationInsights.NLogTarget as a target write log to Azure Application Insights, but I found my console and file targets didn't work, Microsoft.ApplicationInsights.NLogTarget is ok,  what's the reason?

**Comment by SergeyKanzhelev** [comment]
@mstao I'm curious what was the root cause of the issue?

**Comment by imeya** [comment]
@mstao, do you find a solution?
