### ISSUE TITLE
Regression: EventSourceTelemetryModule not setting custom payload properties

### ISSUE THREAD

**Issue by MS-TimothyMothra** [Microsoft/ApplicationInsights-dotnet-logging#173]
This test started failing after #166. This PR merged without running unit tests!

`EventSourceTelemetryModule` isn't calling the `OnEventWrittenHandler`.
https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/46a4db3a1d65246282540102a9e442b5566a89fc/test/EventSourceListener.netcoreapp10.Tests/EventSourceTelemetryModuleTests.cs#L308-L330

It seems that `OnEventWritten` method isn't being invoked.
https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/46a4db3a1d65246282540102a9e442b5566a89fc/src/EventSourceListener/EventSourceTelemetryModule.cs#L145-L160

**Comment by MS-TimothyMothra** [comment]
@pharring if you have time today, can you take a look at this?
This issue will be blocking the next release.

**Comment by karolz-ms** [comment]
@MS-TimothyMothra is only this one test out of all EventSourceTelemetryModule tests that is failing?

It is a bit of a mystery because, at least on a first glance, I do not see anything in Paul's PR that would affect EventSourceTelemetryModule...

**Comment by MS-TimothyMothra** [comment]
@karolz-ms yeah, just this one test.
I suspect it may be related to the new dependency on `System.Diagnostics.TraceSource` for netstandard projects.

**Comment by pharring** [comment]
I just noticed this. Sorry for not getting to it sooner, but I'll look in the morning.
