### ISSUE TITLE
Allow DiagnosticSourceTelemetryModule to take OnEventWrittenHandler like EventSourceTelemetryModule?

### ISSUE THREAD

**Issue by rggammon** [Microsoft/ApplicationInsights-dotnet-logging#180]
EventSourceTelemetryModule constructor accepts a OnEventWrittenHandler parameter, defaulting to EventDataExtensions.Track (which calls CreateTraceTelementry & client.Track())

Would it make sense for DiagnosticSourceTelemetryModule to also provide a constructor that supported a caller-provided OnEventWrittenHandler? Eg, if I wanted to log events instead of traces. Or, https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/111 (which introduced this to EventSourceTelemetryModule), discussed needing this for handling nested EventData - similar reasoning could apply to DiagnosticSourceListenerSubscription.OnNext & event.Value

**Comment by SergeyKanzhelev** [comment]
`DiagnosticSourceTelemetryModule` is a special module. It uploads error logs from SDK for self-monitoring and troubleshooting. We have some dependencies on form of produced telemetry from it.

Why do you want to modify the format of error messages? What is your scenario?

**Comment by rggammon** [comment]
In my particular case, I am logging from an assembly that does not depend on asp.net core. My end goal is to 1) have a way to log custom events to AI and 2) not directly depend on TrackEvent, but log via one of the built-in .net diagnostics sources - EventSource / DiagnosticsSource / TraceSource 

I can see how I can get there via EventSourceTelemetryModule + OnEventWrittenHandler (or write a custom telemetry module) - this is probably what I will do.

I was considering DiagnosticSourceTelemetryModule as well, for its ability to accept complex types (since they don't get serialized & sent cross-process), but this is not critical - eg: I'd prefer to use EventSourceTelemetryModule vs a fork of DiagnosticSourceTelemetryModule 

I think of TraceSource as being optimized for unstructured logging, eg: having a trace listener call TrackEvent seems like the wrong path. 

So, it seems like EventSourceTelemetryModule is my best choice here? Feel free to close, unless we see a path forward here with DiagnosticSourceTelemetryModule .

**Comment by SergeyKanzhelev** [comment]
Oh, I mistaken DiagnosticsSourceTelemetryModule with [DiagnosticsTelemetryModule](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs).

Yes, this callback will be useful.

**Comment by SergeyKanzhelev** [comment]
Do you want to send a PR to implement it?

**Comment by SergeyKanzhelev** [comment]
BTW, there is some work going on to do similar thing for dependency telemetry. In more centralized fashion. See this https://github.com/Microsoft/ApplicationInsights-dotnet/pull/788. Would similar approach be better for Logs?

CC: @lmolkova
