### ISSUE TITLE
Nlog: set user/session id possible?

### ISSUE THREAD

**Issue by fabsenet** [Microsoft/ApplicationInsights-dotnet-logging#195]
I have nlog logging to appinsights. it is configured in the app.config without any keys.

in the program startup I call:
```c#
    const string ik = "123123123...";
    TelemetryConfiguration.Active.InstrumentationKey = ik;
    var tc = new TelemetryClient
    {
        InstrumentationKey = ik
    };

    tc.Context.User.Id = settings.InstallationId.ToString();
    tc.Context.Session.Id = Guid.NewGuid().ToString();
```

I use the TelemetryClient to log pageviews. I see pageviews and traces from nlog in my appinsights. What I want now is to provide the user_id and the session_id in each trace but I do not know how to set this up? the pageviews have a user/session id already.

thanks

**Comment by snakefoot** [comment]
You can setup a custom layout renderer to return the wanted values:

https://github.com/nlog/nlog/wiki/How-to-write-a-custom-layout-renderer

And add contextproperty to output them (See example):

https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/183

**Comment by Dmitry-Matveev** [comment]
Another way you can try is to implement your own [Telemetry Initializer](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling#add-properties-itelemetryinitializer) and assign required properties on the outgoing telemetry. Chances are that `TelemetryClient` used in NLog adapter [is actually created](https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/develop/src/NLogTarget/ApplicationInsightsTarget.cs#L111) with `TelemetryConfiguration.Active` as a configuration, so any initializer you add into applicationinsights.config should be executed for those traces. This is more-less generic AI approach on adding custom properties to the outgoing item.

snakefoot's suggestion, however, seems to be right approach from NLog view on this - you simply expose/propagate the properties you care about.

**Comment by fabsenet** [comment]
It works.

solution was to add this to the app.config:

```xml
<target type="ApplicationInsightsTarget" name="aiTarget">
        <contextProperty name="user_id" layout="${gdc:item=user_id}" />
        <contextProperty name="session_id" layout="${gdc:item=session_id}" />
</target>
```

and somewhere in the app startup:

```cs
GlobalDiagnosticsContext.Set("user_id", "some user id");
GlobalDiagnosticsContext.Set("session_id", "some session id");
```

thanks!
