### ISSUE TITLE
What is HelloWorldTest doing in develop?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-logging#196]
Curious what the purpose of HelloWorldTest in develop branch?

![image](https://user-images.githubusercontent.com/9950081/40764018-1f98648e-645c-11e8-968d-3bb4d33ab074.png)

**Comment by MS-TimothyMothra** [comment]
Our build server wouldn't discover unit tests.
For an unknown reason, including this project was the only way to have tests discovered.
PRs had been accepted for over a month without any test validation and it was blocking a release so I needed the quick fix.

**Comment by SergeyKanzhelev** [comment]
Good to know. If you can just drop a small `README.md` in that folder that repeats this explanation - it will help to avoid confusions.
