### ISSUE TITLE
XML Configuration

### ISSUE THREAD

**Issue by ThunderHorse** [Microsoft/ApplicationInsights-dotnet-logging#198]
Hi Guys, thanks for maintaining this. It doesn't look like you can utilize xml configuration for this external target. Is that correct? I'm just looking to confirm that.

Thanks

**Comment by SergeyKanzhelev** [comment]
I do not follow. Can you elaborate? Are you talking about `ApplicationInsights.config`? If so - it is definitely supported.

**Comment by ThunderHorse** [comment]
@SergeyKanzhelev , sorry for the confusion. I'm referring to using nLog config to add the Application Insights target rather than doing it programatically. After further research I think I've found an example of how to do that. The following link walks through setting it up: 

https://cmatskas.com/working-with-application-insights-and-nlog-in-console-apps-net/

**Comment by SergeyKanzhelev** [comment]
Great! let us know if you'll have more questions.
