### ISSUE TITLE
[NLOG] Add layout support for the ApplicationInsightsTarget target

### ISSUE THREAD

**Issue by ig-sinicyn** [Microsoft/ApplicationInsights-dotnet-logging#201]
Package: Microsoft.ApplicationInsights.NLogTarget, v2.6.4

Scenario: we want to configure the target via xml file and pass instrumentation key obtained from azure key vault.

NLog supports dynamic values via property layouts. Usually, most targets do support things like 
```
// Nlog.config
		<target type="ApplicationInsightsTarget" name="aiTarget" instrumentationKey="${gdc:item=AppInsightsInstrumentationKey}" />

// code
NLog.GlobalDiagnosticsContext.Set(
		"AppInsightsInstrumentationKey",
		instrumentationKeyFromKeyVault);
```

ApplicationInsightsTarget target passes its `instrumentationKey` property as is so the AppInsightsInstrumentationKey value is not expanded.

Please, use Render() for the `InstrumentationKey` property.

**Comment by SergeyKanzhelev** [comment]
Thanks for reporting. Would you like to submit a PR for this?

**Comment by snakefoot** [comment]
Created PR #203
