### ISSUE TITLE
Custom metric showing under "Unavailable/deprecated Metrics"

### ISSUE THREAD

**Issue by m-vani** [Microsoft/ApplicationInsights-dotnet-logging#204]
Hi,

I have added couple of custom metrics few days ago and I see none of them showing up in metrics dashboard. Also, one of them which was fine a week ago is showing up in "Unavailable/deprecated Metrics". I see the counts of the metric getting incremented every day but why is it under the deprecated section? Also, I need help with the newly added custom metrics too. 

Thanks,
Vani
![azure_metrics_issue](https://user-images.githubusercontent.com/40975913/42431942-f549e8dc-8365-11e8-8342-6a6141eea433.png)

**Comment by macrogreg** [comment]
Hi @m-vani ,

Thanks for reporting this. can you please provide a code snippet of how exactly you are sending the data for this metric?

Thanks!

**Comment by m-vani** [comment]
Hi,

I have defined a static class for TelemetryUtils and defined TrackMetric() as shown in the images below. I am calling the custom metrics as below:

I expect to see the metrics **en-GB-Smile-Campaign-Using-Postal-Pin** or **en-GB-Smile-Campaign-Using-QR-Code** show up in the custom metrics but none appears.

![image](https://user-images.githubusercontent.com/40975913/42492340-54b89130-8436-11e8-8baf-a35e30089cfa.png)

![azure_metrics_issue_2](https://user-images.githubusercontent.com/40975913/42492367-751c8eae-8436-11e8-9472-5e5251719a06.png)

**Comment by macrogreg** [comment]
Thanks for the info, @m-vani .
Your API usage is fine for now, however, please note that you are using a non-aggregating metrics API.
I recommend that you consider using the TelemetryClient.GetMetric(..).TrackValue(..) APIs. They are currently in Beta and will be in the next stable release.
However, that is not related to your issue. We are currently looking to figure out what causes the issue you are seeing and we will get back to this thread soon.

**Comment by lgodmer** [comment]
Hi @m-vani 
Could you please provide your applicationId to help with the investigation?
You can find the appId here:
![image](https://user-images.githubusercontent.com/13458748/42544478-e9958008-8466-11e8-89ca-b2923a634ad1.png)
