### ISSUE TITLE
Way to set Cloud Role Name from Config file.

### ISSUE THREAD

**Issue by bodhisatta1984** [Microsoft/ApplicationInsights-dotnet-logging#209]
Please expose a property where we can set the Role Name directly from config file like Instrumentation Key.

**Comment by karolz-ms** [comment]
@bodhisatta1984 you can implement a custom *telemetry initializer* to do just that. See https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling Would that be sufficient for your scenario?

**Comment by snakefoot** [comment]
See also this example: [CloudContextInitializer ](https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/179#issuecomment-385041271)

A new PR that uses NLog Layouts would also work, and would be very simple to implement.
