### ISSUE TITLE
Is there a way to inject my own TelemetryClient?

### ISSUE THREAD

**Issue by marcomorain** [Microsoft/ApplicationInsights-dotnet-logging#21]
I'm using a TelemetryClient in my WPF app to send metrics to App Insights, and I'm using the NLog target for sending logs to App Insights. I initialize both with the same API key, which works great.

I would like to pass my existing `Telemetryclient` in to the `ApplicationInsightsTarget` constructor so that they can share the same client.

I want to have both clients share the same Context, SessionID and User.

```cs
var telemetryClient = new TelemetryClient { InstrumentationKey = instrumentationKey };
telemetryClient.Context.Session.Id = Guid.NewGuid().ToString();
ApplicationInsightsTarget target = new ApplicationInsightsTarget { InstrumentationKey = instrumentationKey };
```

Is there a way to inject my own TelemtryClient? Of not, is there a way to access the Context or otherwise set context of the `TelemetryClient` used by the `ApplicationInsightsTarget`?

Thanks!

Marc

**Comment by abaranch** [comment]
Hi @marcomorain ,
Right now there is no way to access internal TelemetryClient. The only workaround I see is to create ApplicationInsights.config manually (like it is done when you install [Window Server nuget](https://www.nuget.org/packages/Microsoft.ApplicationInsights.WindowsServer/), make sure it gets copied to the output, remove everything from that config, create [TelemetryInitializer that sets context](http://apmtips.com/blog/2014/12/01/telemetry-initializers/) and add it to that configuration file.

**Comment by marcomorain** [comment]
Thanks @abaranch  I've set that up now.
