### ISSUE TITLE
Outdated NuGet package

### ISSUE THREAD

**Issue by wgebczyk** [Microsoft/ApplicationInsights-dotnet-logging#22]
https://www.nuget.org/packages/Microsoft.ApplicationInsights.NLogTarget/

Dependencies
Microsoft.ApplicationInsights (>= 1.2.3)
NLog (>= 2.1.0)

It references 1.2.3 version but when installed with 2.0.1 it simply fails

**Comment by abaranch** [comment]
That you for reporting the issue. We will update logging adapters soon.

**Comment by abaranch** [comment]
@wgebczyk Could you please provide the information on what failure you see? I'm updating reference now but I do not see compatibility issues. I also tried a sample from our readme page and it works fine after the update.

**Comment by abaranch** [comment]
We've just released updated nugets. Though as I said before you should not have had any compatibility issues when updating just AI from 1.2.3 to 2.0.0. So if you still see issues please post it separately with information on what failures you get.
