### ISSUE TITLE
ApplicationInsightsTraceListener & internal TelemetryClient

### ISSUE THREAD

**Issue by funkycoding** [Microsoft/ApplicationInsights-dotnet-logging#23]
Hi,

Using the tracelistener with application insights it does not allow custom properties since it using a internal TelemetryClient to which we do not have access to. Is this something being looked at?

**Comment by abaranch** [comment]
This question is similar to this: #21 
You can add TelemetryInitializer to modify telemetry items.

**Comment by funkycoding** [comment]
Hi @abaranch 
Thanks for your quick response! Note to self: search closed messages :smile: I will have a look at those initializers.
