### ISSUE TITLE
Make NLogTarget's TelemetryClient accessible

### ISSUE THREAD

**Issue by dorfire** [Microsoft/ApplicationInsights-dotnet-logging#234]
For example, I'd like to be able to do this:
`ApplicationInsightsTarget ai = (ApplicationInsightsTarget) LogManager.Configuration.FindTargetByName("ai");`
`ai.TelemetryClient.GetMetric(...);`

**Comment by MS-TimothyMothra** [comment]
I don't see anything wrong with this as an enhancement.

As a workaround so no one is blocked,
You can create your own TelemetryClient in the same way that we do:

https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/5dcd1168d7ed24adb14a9473cb73d2b52b9c3c64/src/NLogTarget/ApplicationInsightsTarget.cs#L113-L122

**Comment by SergeyKanzhelev** [comment]
@dorfire what's wrong with @MS-TimothyMothra suggestion of creating your own telemetry client off the same config?

**Comment by dorfire** [comment]
Nothing particularly wrong with it, but I'd like to re-use the existing client.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by snakefoot** [comment]
Created  #235 as an attempt to resolve this

**Comment by SergeyKanzhelev** [comment]
Reusing is not a good idea as that telemetry client sets specific SDK version which helps troubleshoot. So if you remote metrics with the same client - it will be identified as NLog metrics which will confuse everybody. `TelemetryClient` is intentionally very cheap to instantiate.

I'm closing this PR and issue. Please let me know if you have a reason to reuse.
