### ISSUE TITLE
Document Microsoft.Extensions.Logging.ApplicationInsights logger usage

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet-logging#251]

**Comment by Rick-Anderson** [comment]
When this is completed I'll add links to ASP.NET Core docs. https://github.com/aspnet/Docs/issues/10511

**Comment by cijothomas** [comment]
Completed: 
https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/develop/src/ILogger/Readme.md
