### ISSUE TITLE
.net core DI - how to get TelemetryClient

### ISSUE THREAD

**Issue by MikeAtETI** [Microsoft/ApplicationInsights-dotnet-logging#278]
I configure a ServiceProvider, add AI logging through:

 sc.AddLogging(
                builder =>
                {
                    builder.AddApplicationInsights("XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX");
                    builder.AddFilter<ApplicationInsightsLoggerProvider>("", LogLevel.Trace);
                });

If I try and do ServiceProvider.GetRequiredService<TelemetryClient> it always throws an exception.

**Comment by cijothomas** [comment]
@MikeAtETI Please completely describe what you are trying to do and how. The post seems imcomplete?

**Comment by MikeAtETI** [comment]
I'm trying to track an event (or a  pageview) to the same Application Insights as the main ILogger bits are going to. I could be missing something as I'm new at this, but it looks like the TelemetryClient is what I need but it would need all the telemetryinitializers etc re-hooking to it?

**Comment by cijothomas** [comment]
@MikeAtETI please check if the docs help you to get started : https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger

By installing just Microsoft.Extensions.Logging.ApplicationInsights, you'll *not* get TelemetryClient from DI. its injected only if using Microsoft.ApplicationInsights.AspNetCore.

**Comment by pharring** [comment]
I bumped into this too, but after a bit of digging, I was happy when I figured out that, with just the ILogger's `AddApplicationInsights()` extension method, I could use `IOptions<TelemetryConfiguration> telemetryOptions` in my controllers:

i.e.
```csharp
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.Extensibility;
using Microsoft.Extensions.Options;
// etc.

public class MyController : ApiController
{
   private readonly TelemetryClient _telemetryClient;
   private readonly ILogger _logger;

   public MyController(IOptions<TelemetryConfiguration> options, ILogger<MyController> logger)
   {
        _telemetryClient = new TelemetryClient(options.Value);
        _logger = logger;
   }

  // etc.
}
```

**Comment by cijothomas** [comment]
@pharring Thanks! I was updating the docs with information on how to get TC used by ilogger.

**Comment by MikeAtETI** [comment]
@pharring @cijothomas thanks - that does exactly what I need

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#frequently-asked-questions FAW updated to included this .
