### ISSUE TITLE
Use custom TelemetryClient

### ISSUE THREAD

**Issue by alincosmin7** [Microsoft/ApplicationInsights-dotnet-logging#279]
I’m using Application Insights in a WebJob with a triggered function.
I need to use a custom TelemetryClient to set Session ID 

My previous code was registering TelemetryClient like this
```
services.Add(
	new ServiceDescriptor(typeof(TelemetryClient), 
	provider => provider.GetService<ITelemetryClientFactory>().Create(appInsightsKey, functionName), 
	ServiceLifetime.Scoped));

services.AddScoped<ILoggerFactory, LoggerFactory>(serviceProvider=>
{
	var loggerFactory = new LoggerFactory();
	loggerFactory.AddApplicationInsights(serviceProvider);
	return loggerFactory;
});
```
How to make Application insights when added with loggingBuilder to use my custom Telemetry Client

**Comment by cijothomas** [comment]
can you describe the issue a bit more clearer - how was your code before, and how is it now, and what is the difference in observed behavior.

**Comment by alincosmin7** [comment]
@cijothomas  In fact I want to use my custom TelemetryClient as it was working in my previous code:

**Previous code:**

```
services.AddScoped<ILoggerFactory, LoggerFactory>(serviceProvider=>
{
	var loggerFactory = new LoggerFactory();
	loggerFactory.AddApplicationInsights(serviceProvider); // this is deprecated now
	return loggerFactory;
});

```
**New recommended way to add Application Insights logger**

```
services.AddLogging(loggingBuilder => {
	    loggingBuilder.AddFilter<ApplicationInsightsLoggerProvider>("", LogLevel.Trace);
            loggingBuilder.AddApplicationInsights("--YourAIKeyHere--");         
            }); 
```

**Comment by RamjotSingh** [comment]
ILogger extensions for Application insights uses it's own TelemetryClient. You can use [ITelemetryInitializer or ITelemeryProcessor](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling) to set additional metadata on outgoing telemetry items.

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet-logging/issues/278#issuecomment-482296406 Check this comment if you are looking to create own TelemetryClient with same config used by ILogger.

**Comment by cijothomas** [comment]
FAQ updated to include explanation on how to get a TC when using ilogger.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#frequently-asked-questions
