### ISSUE TITLE
Microsoft.ApplicationInsights.EtwCollector: Please allow .Net 4.5 projects to use Microsoft.ApplicationInsights.EtwCollector

### ISSUE THREAD

**Issue by Pankaj-Thakur** [microsoft/ApplicationInsights-dotnet-logging#295]
I cloned and built https://github.com/microsoft/ApplicationInsights-dotnet-logging/blob/develop/src/EtwCollector/EtwCollector.csproj fine with <TargetFrameworks>net45</TargetFrameworks>; in place of <TargetFrameworks>net451</TargetFrameworks>. 

Please allow more projects to use it. While we would love to be on the latest .Net framework version it is not always feasible.

**Comment by MS-TimothyMothra** [comment]
@cijothomas @Dmitry-Matveev @SergeyKanzhelev 
**Does anyone know if there's a historical reason that our Logging SDKs are on NET4.5.1 while our Base SDK is on NET4.5?**

I'm not certain that dropping support for 4.5.1 is the right solution, will this downgrade affect customers?
I see no technical reason why we can't support both 4.5 and 4.5.1.
However, it's worth noting that BOTH 4.5 and 4.5.1 are no longer supported. While we're discussing framework versions, we should also discuss why are we not on 4.5.2.

### Our other SDKs
- [BaseSDK (net45;net46;netstandard1.3;netstandard2.0)](https://github.com/microsoft/ApplicationInsights-dotnet/blob/9405f131a9689a4290af37e7e53151a1f4d789fd/src/Microsoft.ApplicationInsights/Microsoft.ApplicationInsights.csproj#L6)
- [WebSDK (net45)](https://github.com/microsoft/ApplicationInsights-dotnet-server/blob/ec904d01fce16e0e2c223a83829207fea0f30486/Src/Web/Web/Web.csproj#L8)

### .NET Versions
- https://github.com/Microsoft/dotnet/blob/master/releases/README.md

### Support Ending for the .NET Framework 4, 4.5 and 4.5.1
- https://devblogs.microsoft.com/dotnet/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by karolz-ms** [comment]
I am the original author of this code. I do not remember exact details but I am 99% certain there were bugs in the original implementation of .NET 4.5 that made it impossible for the EtwCollector to work properly (AFAIR around event parameter value acquisition). That is why this module took dependency on .NET 4.5.1 specifically.

From "secure by default" and "quality is #1 priority" perspective we should probably do the opposite of what this issue suggests, namely, target 4.5.2 as means of supporting 4.5 series of .NET FX. This is to ensure that customer are picking up fixes for the known functional and security issues.

**Comment by cijothomas** [comment]
Thanks @karolz-ms and @xiaomi7732 for sharing comments. Based on the comments, it'd best to not increase support matrix to increase to net45 as well.
