### ISSUE TITLE
Creating new instance of ApplicationInsightsTarget takes ~300ms

### ISSUE THREAD

**Issue by thisisthekap** [microsoft/ApplicationInsights-dotnet-logging#308]
Creating a new instance of `ApplicationInsightsTarget` takes about 300ms using Xamarin.Android on a Nexus 6P.

As this happens during app startup, this value is imho way too high.

**Comment by cijothomas** [comment]
Please reopen and share more information to take any action. Which SDK, version etc.

**Comment by thisisthekap** [comment]
I am using Microsoft.ApplicationInsights.NLogTarget 2.10.0.

**Comment by thisisthekap** [comment]
@cijothomas I think i am unable to reopen the issue. Could you please do so?

**Comment by thisisthekap** [comment]
@cijothomas Can you please reopen the issue?
