### ISSUE TITLE
Log time conversions - Display raw value/UTC time

### ISSUE THREAD

**Issue by mbryant2** [Microsoft/ApplicationInsights-dotnet-logging#46]
Note: Not sure if this needs to be posted here, or sent to the parent portal group.
Currently the times of logs being sent to App Insights are logged via UTC at least in our particular use case.  we have two different logging locations currently, one in SQL and one here in Application Insights. 

When running a search in application insights the logging values are populated in whatever time zone is currently set to the computer.  While this is helpful for regional debugging in quick succession, in trying to tie events together that are listed in UTC, there is often significant time spent on trying to correlate time stamps.

It would be nice if the logging item displayed the saved time in UTC or some other standard item, so when multiple people, in geographically dispersed locations can focus quickly on identifying items.

An enhancement that could be added to the logging portion to help create a shortcut, is an added field that showed the default UTC time of a logging event.  This would help get around the portal time conversions, and the same value could be referenced twice, while still providing a true accounting of the time the action was preformed.

**Comment by SergeyKanzhelev** [comment]
So you are saying that traces are collected in UTC and than displayed in local time. But if it is the case - what's the issue correlating them between location? Or you try to correlate with the other source of telemetry?

**Comment by mbryant2** [comment]
We are trying to correlate the two sources of telemetry.  Another option would be to at least provide the UTC +/-X as part of the date time string.  This would at least get us generally closer with a little less effort.  Because our team is dispersed, and travels, time zones tend to be roadblocks, as well as our input dates from our external endpoints are captured in UTC.

**Comment by SergeyKanzhelev** [comment]
I'm sorry for the delay. I lost track of this issue. Application Insights collects data in UTC and shows it in viewer's time in Azure portal and UTC in Analytics view. 

If you need to know the timezone of the computer collecting telemetry - you'll need to add this information as a custom property to the telemetry items. You can implement a [telemetry initializer](http://apmtips.com/blog/2014/12/01/telemetry-initializers/) to do it.

**Comment by SergeyKanzhelev** [comment]
Feel free to re-open the issue if you believe Application Insights should change it's default behavior.
