### ISSUE TITLE
Custom telemetry initializer is not used

### ISSUE THREAD

**Issue by Olif** [Microsoft/ApplicationInsights-dotnet-logging#53]
I have a custom telemetry initializer which adds the current environment to the AI logs.

```
public class EnvironmentTelementryInitializer : WcfTelemetryInitializer
	{
	    public const string PropertyName = "Env";

	    private readonly string _environment;

	    public EnvironmentTelementryInitializer()
        {
            _environment = ConfigurationManager.AppSettings["EnvironmentName"];
        }

	    protected override void OnInitialize(ITelemetry telemetry, IOperationContext operation)
	    {
	        telemetry.Context.Properties[PropertyName] = _environment;
	    }
	}
```

Even though the initializer is added to the collection of initializers in ApplicationInsights.Config the AI logs does not contain the "Env" property. 

I'm also using the RequestTrackingTelemetryModule and there the Env property is set so it seems that the NLogTarget does not use the custom intializers specified in ApplicationInsight.config

**Comment by Olif** [comment]
Ok, I resolved the issue.

I added my custom Initializer last in the Application.Insights <TelemetryInitializers> list and now it works. I.e there is a bug somewhere but not in this library,

**Comment by SergeyKanzhelev** [comment]
I'm glad it worked.

**Comment by SergeyKanzhelev** [comment]
BTW, what is the reason for you to separate environments by custom property, not create an instrumentation key per environment?

**Comment by Olif** [comment]
Hi.

The reason is that we have lot's of applications and lots of environment
for each application so instead of having lots of application insights
"applications" to manage in the azure portal, we are collecting all logs on
one instrumentation key and filter the messages based on the Env variable.

Have a nice day!
/Niklas

2016-09-12 18:42 GMT+02:00 Sergey Kanzhelev <notifications@github.com>:
