### ISSUE TITLE
Inconsistent logging of role instance name between WAD2AI and .NET SDK

### ISSUE THREAD

**Issue by FrictionFree** [Microsoft/ApplicationInsights-dotnet-logging#56]
Performance counters reported by WAD2AI integration use the logical name of the Web Role (e.g. WebRole1_IN_3) while performance counters reported by the regular .NET SDK use the VM name (RD0003FF93FDC0).

Repro:
I have the latest AI SDK and latest Azure Cloud Tools. I have created a new Web Role and enabled WAD2AI through the UX in VS. Run some requests...
See attached.

![inconsistentroleinstancename](https://cloud.githubusercontent.com/assets/19516037/19716300/b311dbf0-9b63-11e6-8794-24d01282e7ef.jpg)

**Comment by SergeyKanzhelev** [comment]
Thanks for reporting! It is a dup for this item: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/168
