### ISSUE TITLE
Add custom property to Log4Net adapter

### ISSUE THREAD

**Issue by Shachar1** [Microsoft/ApplicationInsights-dotnet-logging#7]
Hi, I'm trying to add a custom property to my log4net adapter so I can use it as a filter parameter in Application Insights.

I've tried -
In the config:
 
```xml
<parameter>
   <parameterName value="@CustomColumn"/>
   <dbType value="String" />
   <size value="255" />
   <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%property{CustomColumn}" />
  </layout>
</parameter>
```
and then : 
log4net.LogicalThreadContext.Properties["CustomColumn"] = "Custom value";

But I don't see the custom property in Application Insights dashboard.

Thanks.

**Comment by abaranch** [comment]
Thank you for reporting the issue. We will investigate it and replyback to you.

**Comment by ChrisMeeusen** [comment]
Is this working now?  Im not able to log out threadcontextproperties through the appender
