### ISSUE TITLE
Common.logging adapter?

### ISSUE THREAD

**Issue by dsschnau** [Microsoft/ApplicationInsights-dotnet-logging#74]
Hi,

I have an app that writes to the [Common.Logging](http://netcommon.sourceforge.net/) project with [another package that connects common.logging to log4net](https://www.nuget.org/packages/Common.Logging.Log4Net1215/3.3.1). I am able to use the Application Insights Log4Net adapter from there, but I'm wondering if there's a better way.

Is it possible to create a Common.Logging adapter? Is there any reason one doesn't exist already, other than lack of demand?

**Comment by SergeyKanzhelev** [comment]
You'd be first asking it on github. Would you like to contribute - it would be quite straightforward implementation. Or have a side implementation we can refer people to... And since you are using it - you can make it work "right" in the `Common.Logging`'s terms

**Comment by dsschnau** [comment]
Thanks for the response - after consulting with my team, we decided the value isn't really there to bother building this adapter. As stated, we have our existing solution (common.logging -> log4net -> Application Insights) and there is new development is using Common.Logging.

So I'm going to close this issue.
