### ISSUE TITLE
Logary

### ISSUE THREAD

**Issue by Thorium** [Microsoft/ApplicationInsights-dotnet-logging#81]
Hello,

AppInsights target for [Logary](https://github.com/logary/logary) would be nice.

**Comment by SergeyKanzhelev** [comment]
@Thorium would you be interested creating and supporting one? We will definitely link it from our documentation if you will want to do it. 

We are trying to cover basics and support trace adaptors for the most popular frameworks. Similar request was recently for `Common.logging`: https://github.com/Microsoft/ApplicationInsights-dotnet-logging/issues/74

**Comment by Thorium** [comment]
Done. Not to this repo, but as a separate [NuGet-package](https://www.nuget.org/packages/Logary.Targets.AppInsights/) as other Logary targets.

**Comment by SergeyKanzhelev** [comment]
Nice! https://github.com/Microsoft/azure-docs/pull/1498#issuecomment-296315344
