### ISSUE TITLE
Add a DiagnosticSourceListener module

### ISSUE THREAD

**Issue by pharring** [Microsoft/ApplicationInsights-dotnet-logging#89]
For Snapshot Collector, I created a general purpose TelemetryModule that listens to DiagnosticSource and tracks them via Application Insights. It's the DiagnosticSource equivalent of Microsoft.ApplicationInsights.EventSourceListener

Are you interested in including it here? I'll do the work and submit a PR, I just want to know if you're interested before I embark on porting it.

**Comment by SergeyKanzhelev** [comment]
Yes, we need to have support for all Framework sources in-house. If you can create on - we'll take it

**Comment by pharring** [comment]
Closed via #90
