### ISSUE TITLE
Can the log level be configured for Microsoft.ApplicationInsights.TraceListener?

### ISSUE THREAD

**Issue by codecadwallader** [Microsoft/ApplicationInsights-dotnet-logging#91]
When using the Microsoft.ApplicationInsights.TraceListener NuGet package the following lines are added to the Web.config file:

``` 
<system.diagnostics>
    <trace autoflush="true" indentsize="0">
      <listeners>
        <add name="myAppInsightsListener" type="Microsoft.ApplicationInsights.TraceListener.ApplicationInsightsTraceListener, Microsoft.ApplicationInsights.TraceListener" />
      </listeners>
    </trace>
  </system.diagnostics>
```

By default it looks like it collects all traces (including informational).  Is there a configuration change that can be used to change the log level (e.g. warning)?

**Comment by SergeyKanzhelev** [comment]
Sure, it is just a regular trace provider. See examples here: http://apmtips.com/blog/2014/11/13/collect-asp-dot-net-mvc-web-api-traces-with-application-insights/

**Comment by codecadwallader** [comment]
Perfect, thank you!
